name: Deploy to production

on:
  workflow_run:
    workflows: [ "Build Dockerfile and push to registry" ]
    branches: [ v[0-9]+.[0-9]+.[0-9]+ ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ${{ secrets.SSH_SCRIPT }}